[config]

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = './generated/gtk-3.css'
post_hook = "gsettings set org.gnome.desktop.interface icon-theme 'Fluent-teal-dark'"

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = './generated/gtk-4.css'
post_hook = 'mkdir -p $HOME/.config/gtk-3.0 $HOME/.config/gtk-4.0; ln -nfs ./generated/gtk-3.css $HOME/.config/gtk-3.0/gtk.css; ln -nfs ./generated/gtk-4.css $HOME/.config/gtk-4.0/gtk.css; gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"; systemctl --user reset-failed hyprpolkitagent; systemctl --user restart hyprpolkitagent || true'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = './generated/qt5ct-colors.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = './generated/qt6ct-colors.conf'

[templates.swaync]
input_path = './templates/colors.css'
output_path = './generated/swaync-colors.css'
post_hook = 'swaync-client -rs || true'

[templates.swayosd]
input_path = './templates/swayosd-colors.css'
output_path = './generated/swayosd-colors.css'
post_hook = '$HOME/.user_scripts/swayosd/restart_swayosd.sh'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = './generated/kitty-colors.conf'
post_hook = 'ln -nfs ./generated/kitty-colors.conf $HOME/.config/kitty/kitty-colors.conf; pkill -SIGUSR1 kitty || true'

[templates.neovim]
input_path = './templates/neovim-colors.lua'
output_path = './generated/neovim-colors.lua'
post_hook = 'pkill -SIGUSR1 nvim || true'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = './generated/yazi-theme.toml'
post_hook = 'ln -nfs ./generated/yazi-theme.toml $HOME/.config/yazi/theme.toml'

[templates.zathura]
input_path = './templates/zathura-colors'
output_path = './generated/zathura-colors'
post_hook = 'ln -nfs ./generated/zathura-colors $HOME/.config/zathura/zathurarc'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = './generated/starship-colors.toml'
post_hook = 'ln -nfs ./generated/starship-colors.toml $HOME/.config/starship.toml'

[templates.tmux]
input_path = './templates/tmux-colors.conf'
output_path = './generated/tmux-colors.conf'
post_hook = 'tmux source-file ./generated/tmux-colors.conf'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = './generated/pywalfox-colors.json'
post_hook = 'ln -nfs ./generated/pywalfox-colors.json $HOME/.cache/wal/colors.json; pywalfox update || true'

[templates.btop]
input_path = './templates/btop.theme'
output_path = './generated/btop-colors.theme'
post_hook = 'mkdir -p $HOME/.config/btop/themes; ln -nfs ./generated/btop-colors.theme $HOME/.config/btop/themes/matugen.theme'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = './generated/rofi-colors.rasi'

[templates.obsidian]
input_path = './templates/obsidian-theme.css'
output_path = './generated/obsidian-theme.css'
post_hook = 'mkdir -p $HOME/Documents/pensive/.obsidian/snippets; ln -nfs ./generated/obsidian-theme.css $HOME/Documents/pensive/.obsidian/snippets/matugen-theme.css'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = './generated/hyprland-colors.conf'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = './templates/hyprlock-colors.conf'
output_path = './generated/hyprlock-colors.conf'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = './generated/wlogout-colors.css'

[templates.spicetify]
input_path = './templates/spotify-colors.ini'
output_path = './generated/spotify-colors.ini'
post_hook = 'killall -SIGUSR2 spotify; mkdir -p $HOME/.config/spicetify/Themes/Comfy; ln -nfs ./generated/spotify-colors.ini $HOME/.config/spicetify/Themes/Comfy/color.ini; spicetify config current_theme Comfy color_scheme Comfy; spicetify apply -n'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = './generated/cava-colors.ini'
post_hook = 'mkdir -p $HOME/.config/cava/themes; ln -nfs ./generated/cava-colors.ini $HOME/.config/cava/themes/cava-colors.ini; pkill -USR1 cava || true'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = './generated/alacritty-colors.toml'
post_hook = 'ln -nfs ./generated/alacritty-colors.toml $HOME/.config/alacritty/alacritty-colors.toml'

[templates.waybar]
input_path = './templates/colors.css'
output_path = './generated/waybar-colors.css'
post_hook = 'pkill -SIGUSR2 waybar || true; notify-send "Theme Updated"'
